name = "SDPLRPlus"
uuid = "9040bce9-cc75-4a86-9224-0257f72befc6"
authors = ["luotuoqingshan <2019hyf@gmail.com>"]
version = "0.1.1"

[deps]
GenericArpack = "408c25d7-97fa-4992-8bd9-ce15f1a09fe9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LowRankOpt = "607ca3ad-272e-43c8-bcbe-fc71b56c935c"
LuxurySparse = "d05aeea4-b7d4-55ac-b691-9e7fabb07ba2"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
MKLSparse = "0c723cd3-b8cd-5d40-b370-ba682dde9aae"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
GenericArpack = "0.2"
LowRankOpt = "0.2.1"
LuxurySparse = "0.7, 0.8"
MKL = "0.6, 0.7"
MKLSparse = "1, 2"
NLPModels = "0.21.5"
Parameters = "0.12"
PolynomialRoots = "1"
Polynomials = "4"
SolverCore = "0.3.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
