[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
CSDP = "0a46da34-8e4b-519e-b418-48813639ff34"
LuxurySparse = "d05aeea4-b7d4-55ac-b691-9e7fabb07ba2"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
SDPLRPlus = "9040bce9-cc75-4a86-9224-0257f72befc6"
